CREATE DATABASE ecommerce;

USE ecommerce;

CREATE TABLE tb_user (
    user_id CHAR(36) PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    cpf CHAR(11) NOT NULL UNIQUE,
    email VARCHAR(250) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    admin BOOLEAN NOT NULL DEFAULT FALSE,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
